name: SDLC Workflow

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  all-tests:
    uses: dogmatic69/nordigen-python/.github/workflows/all-test.yaml@master
    with:
      fetch_depth: 0
    secrets:
      github_key: ${{ secrets.GITHUB_TOKEN }}
      sonar_key: ${{ secrets.SONAR_TOKEN }}

  publish:
    uses: dogmatic69/nordigen-python/.github/workflows/pypi-publish.yaml@master
    if: github.ref == 'refs/heads/master'
    needs:
      - all-tests
    with:
      python_version: 3.10
    secrets:
      pypi_key: ${{ secrets.PYPI_TOKEN }}

