name: PyPi Publish

on:
  workflow_call:
    inputs:
      python_version:
        required: false
        type: string
        default: '3.10'
      package_name:
        required: true
        type: string
    secrets:
      pypi_key:
        required: true
        description: API token for access to PyPI

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      local-version: ${{ steps.local-version.outputs.version }}
      remote-version: ${{ steps.remote-version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - id: local-version
        run: echo "::set-output name=version::$(cat VERSION)"
      - id: remote-version
        run: echo "::set-output name=version::$(pypi info ${{ inputs.package_name }} | grep Latest | awk '{print $3}')"
      - name: Version Info
        run: |
          echo "Local Version: ${{ steps.local-version.outputs.version }}"
          echo "Remote Version: ${{ steps.remote-version.outputs.version }}"

  publish-package:
    runs-on: ubuntu-latest
    needs:
      - version
    if: needs.version.outputs.local-version != needs.version.outputs.remote-version
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python Version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python_version }}
      - name: setup
        run: make install-publish
      - name: publish
        run: make publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_key }}
