name: PyPi Publish

on:
  workflow_call:
    inputs:
      python_version:
        type: string
        default: 3.10
    secrets:
      pypi_key:
        required: true
        description: API token for access to PyPI

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python Version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python_version }}
      - name: setup
        run: make install-publish
      - name: publish
        run: make publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_key }}
